#!/bin/sh
#   Script by Ypnose  <linuxien[AT]legtux[DOT]org>
#   Inspired by afur-makepkg wrote by Tuxce
#
#   Upload packages on Archlinux.fr private FTP
#   This script is POSIX compliant, it should work with every shells.
#   It just needs curl
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#  
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#  
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#   MA 02110-1301, USA.
#  

SOFT="afuryc"
VERS="1.0"
COMPILE=1
UPLFTP=1
CLEAN=0

usage () {
	printf "usage:  %s <options>\n" "$SOFT"
	printf "  options:\n"
	printf "    -c        Create packages without upload\n"
	printf "    -d        Clean existing src/ and pkg/ directories\n"
	printf "    -e        Edit PKGBUILD\n"
	printf "    -h        Show help\n"
	printf "    -r        Edit config file\n"
	printf "    -u        Only upload packages to FTP\n"
	printf "%s compiles packages and upload them to Archlinux.fr FTP.\n\n" "$SOFT"
}

checkconf () {
	if [ -r "$HOME/.afuryc.conf" ]; then
		. $HOME/.afuryc.conf
	fi
	if [ -r "$HOME/.config/afuryc.conf" ]; then
		. $HOME/.config/afuryc.conf
	fi
	if [ ! -r "$HOME/.afuryc.conf" ] && [ ! -r "$HOME/.config/afuryc.conf" ]; then
		printf "Config file not found. You should create a config file.\nExiting\n"
		exit 1
	fi
}

changeconf () {
	if [ ! -r "$HOME/.afuryc.conf" ] && [ ! -r "$HOME/.config/afuryc.conf" ]; then
		printf "Config file not found. You should create a config file.\nExiting\n"
		exit 1
	fi
	if [ -r "$HOME/.afuryc.conf" ]; then
		$EDITOR $HOME/.afuryc.conf
	fi
	if [ -r "$HOME/.config/afuryc.conf" ];then
		$EDITOR $HOME/.config/afuryc.conf
	fi
	printf "Configs modified!\nDone\n"
}

build () {
	makepkg
	makepkg --source
}

cleanbuild () {
	if [ -d "src" ] || [ -d "pkg" ]; then
	while true; do
		printf "Do you want to delete src/ & pkg/ folders? [Y/n] "
		read ask
		case $ask in
			[Yy])
			  printf "Deleting existing src/ and pkg/ folder!\n"
			  rm -r src pkg
			  break
			  ;;
			[Nn])
			  break
			  ;;
			*)
			  printf "Please answer yes or no!\n"
			  ;;
		esac
	done
	else
		printf "The directories are missing!\n"
	fi
}

edit () {
	if [ -n "$EDITOR" ]; then
		if [ -r "PKGBUILD" ]; then
			$EDITOR PKGBUILD
			printf "Edit finished\n"
		else
			printf "PKGBUILD doesn't exist\n"
		fi
	else
		printf '$EDITOR is not defined\n'
	fi
}

upload () {
	checkconf
	printf "The following packages will be uploaded\n"
	#for pkg in ""
		#do
			#echo
	#done
	printf "Uploading packages...\n"
		#for pkg in ""
		#do
			#curl -u "$USERF":"$PASSF" -T "$pkg" "$FTPURL"
	#done
}

if [ "$1" = "-help" ]; then
	usage
	exit 0
fi

while getopts "cdehru" opt; do
	case $opt in 
		c)
		  UPLFTP=0
		  ;;
		d)
		  CLEAN=1
		  ;;
		e)
		  edit
		  exit 0
		  ;;
		h)
		  usage
		  exit 0
		  ;;
		r)
		  changeconf
		  exit 0
		  ;;
		u)
		  COMPILE=0
		  ;;
		:)
		  printf "NEEDARG\n"
		  exit 1
		  ;;
		?)
		  printf "%s: This option is invalid '-$OPTARG'\n" "$SOFT"
		  exit 1
		   ;;
	esac
done

if [ "$((CLEAN))" -ne 0 ]; then
	cleanbuild
fi

if [ "$((COMPILE))" -ne 0 ]; then
	checkconf
	build
fi

if [ "$((UPLFTP))" -ne 0 ]; then
	upload
fi

exit 0





